name: Update README with Problem Count and Index

on:
  push:
    paths:
      - "**/*.cpp"
      - "**/*.py"
      - "**/*.java"
      - "**/*.md"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync with remote
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Count problems
        id: count
        run: |
          COUNT=$(find . -type f \( -name "*.cpp" -o -name "*.py" -o -name "*.java" \) | wc -l)
          echo "COUNT=$COUNT" >> $GITHUB_ENV

      - name: Generate index table
        run: |
          INDEX="| # | Problem Name | Link |\n|---|--------------|------|\n"
          i=1
          for dir in $(find . -maxdepth 1 -type d ! -path . | sort); do
            problem=$(basename "$dir")
            INDEX+="| $i | $problem | [$problem]($problem) |\n"
            i=$((i+1))
          done
          echo -e "$INDEX" > index_table.md

      - name: Update README
        run: |
          COUNT_BADGE="![Problems Solved](https://img.shields.io/badge/Problems%20Solved-$COUNT-brightgreen)"
          awk -v badge="$COUNT_BADGE" 'NR==1{print badge} {print}' README.md > temp && mv temp README.md

          # Append Index Table
          echo -e "\n## 📚 Problem Index\n" >> README.md
          cat index_table.md >> README.md

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Auto-update README: problem count & index" || echo "No changes to commit"
          git push origin main
